import pytz

CONSUMER_KEY        = 'XXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN        = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

TWITTER_ACCOUNT = 'XXXXXXXX'

TIME_ZONE = pytz.timezone('Asia/Tokyo')

PIXELA_USER = 'XXXXXXXX'
PIXELA_TOKEN = 'XXXXXXXX'
PIXELA_ID = 'XXXXXXXX'